title: SAHIL KOMMALAPATI
description: Fluid Mechanics and Artificial Intelligence researcher at the University of Washington. 
show_downloads: True
google_analytics:
theme: jekyll-theme-minimal
logo: True
github:
  zip_url: https://scholar.google.co.in/citations?hl=en&user=QqqnDkYAAAAJ
  tar_url: https://www.linkedin.com/in/kommalapati/
  git_url_: https://github.com/kommalapatisahil
  medium_url: https://medium.com/@kommalapatisahil
  resume_url: https://github.com/kommalapatisahil/bio/blob/master/CV_SK.pdf
  
